[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

; シリアルモニタ速度
monitor_speed = 115200

; 書き込み速度 (失敗する場合は 460800 に下げる)
upload_speed = 921600

; BLEライブラリ (ESP32パッケージに含まれるため追加不要)
